models:
    1D_CNN:
        API_KEY: "put_you_key_here"
        lr: 0.001
        stride : 1
        batch_size : 32
        num_epochs: 10
        vocab_size: 5000
        embedding_dim: 100
        output_dim: 128
        num_classes: 3
        kernel_size: 3
        num_filters: 100
        
    BERT:
        API_KEY: "put_you_key_here"
        num_epochs: 3
        max_length: 128
        num_labels: 3
        batch_size: 32
        lr: 0.00002


